[project]
name = "learnhiragana"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nuitka>=2.6.9",
    "rich>=14.0.0",
]
